import Cocoa
import FlutterMacOS

/// relic/clipboard — the NSPasteboard operations the cross-platform plugins
/// don't cover: the change counter, privacy markers, Finder file copies, raw
/// TIFF fallback and sensitive writes. Dart client:
/// app/lib/platform/src/macos/clipboard_macos.dart.
enum ClipboardBridge {
  /// Community pasteboard-privacy markers (http://nspasteboard.org) —
  /// password managers set these so history tools skip the entry.
  static let concealed = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
  static let transient = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
  /// Machine-written content (an app filling the pasteboard on the user's
  /// behalf) — not a user copy, so it never belongs in history.
  static let autoGenerated =
    NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

  static func register(with messenger: FlutterBinaryMessenger) {
    let channel = FlutterMethodChannel(name: "relic/clipboard", binaryMessenger: messenger)
    channel.setMethodCallHandler { call, result in
      let pb = NSPasteboard.general
      switch call.method {
      case "changeCount":
        result(pb.changeCount)

      case "shouldBeIgnored":
        let types = pb.types ?? []
        result(types.contains(concealed) || types.contains(transient) ||
               types.contains(autoGenerated))

      case "clear":
        pb.clearContents()
        result(true)

      case "markSensitive":
        // Append the marker types to whatever is on the pasteboard now. The
        // marker's *presence* is the signal; its data is irrelevant.
        pb.addTypes([concealed, transient], owner: nil)
        pb.setData(Data(), forType: concealed)
        pb.setData(Data(), forType: transient)
        result(true)

      case "writeSensitiveText":
        guard let args = call.arguments as? [String: Any],
              let text = args["text"] as? String else {
          result(false)
          return
        }
        pb.clearContents()
        pb.declareTypes([.string, concealed, transient], owner: nil)
        let ok = pb.setString(text, forType: .string)
        pb.setData(Data(), forType: concealed)
        pb.setData(Data(), forType: transient)
        result(ok)

      // Text plus its formatting flavors, in ONE pasteboard session.
      //
      // Deliberately not super_clipboard's writer (which the photo path uses):
      // that declares a lazy NSPasteboardWriter promise, so the content dies
      // when Relic quits, and its clearContents() would wipe the privacy
      // markers we set here. Declaration order is the app's preference order,
      // so the rich types lead and .string is the fallback every app can take.
      case "writeRich":
        guard let args = call.arguments as? [String: Any],
              let text = args["text"] as? String else {
          result(false)
          return
        }
        let html = args["html"] as? String
        let rtf = (args["rtf"] as? FlutterStandardTypedData)?.data
        let sensitive = (args["sensitive"] as? Bool) ?? false

        var types: [NSPasteboard.PasteboardType] = []
        if rtf != nil { types.append(.rtf) }
        if html != nil { types.append(.html) }
        types.append(.string)
        if sensitive { types.append(contentsOf: [concealed, transient]) }

        pb.clearContents()
        pb.declareTypes(types, owner: nil)
        var wrote = pb.setString(text, forType: .string)
        if let rtf = rtf { wrote = pb.setData(rtf, forType: .rtf) && wrote }
        if let html = html {
          // The charset marker keeps Notes and Mail from assuming latin-1.
          let marked = "<meta charset='utf-8'>" + html
          wrote = pb.setString(marked, forType: .html) && wrote
        }
        if sensitive {
          pb.setData(Data(), forType: concealed)
          pb.setData(Data(), forType: transient)
        }
        result(wrote)

      case "filePaths":
        let opts: [NSPasteboard.ReadingOptionKey: Any] = [.urlReadingFileURLsOnly: true]
        let urls = pb.readObjects(forClasses: [NSURL.self], options: opts) as? [URL] ?? []
        result(urls.map { $0.path })

      case "rawImage":
        // TIFF is macOS's native raster interchange; sources that don't add a
        // PNG rep (some screenshot paths, drawing apps) still provide this.
        if let data = pb.data(forType: .tiff) {
          result(FlutterStandardTypedData(bytes: data))
        } else {
          result(nil)
        }

      case "writeFile":
        guard let args = call.arguments as? [String: Any],
              let path = args["path"] as? String else {
          result(false)
          return
        }
        let url = URL(fileURLWithPath: path)
        pb.clearContents()
        let ok = pb.writeObjects([url as NSURL])
        if ok {
          pb.addTypes([concealed, transient], owner: nil)
          pb.setData(Data(), forType: concealed)
          pb.setData(Data(), forType: transient)
        }
        result(ok)

      default:
        result(FlutterMethodNotImplemented)
      }
    }
  }
}
