import 'package:flutter/services.dart';

/// macOS backend of platform/clipboard_bridge.dart: a thin client over the
/// `relic/clipboard` MethodChannel implemented by
/// macos/Runner/Bridge/ClipboardBridge.swift (NSPasteboard). Every call is
/// best-effort: a missing channel (e.g. before the Swift side is registered)
/// degrades to the same benign empty results the Windows guards return.

const _ch = MethodChannel('relic/clipboard');

/// NSPasteboard.general.changeCount — bumps on every clipboard write, the
/// direct analog of Windows' GetClipboardSequenceNumber. 0 on failure.
Future<int> changeCount() async {
  try {
    return await _ch.invokeMethod<int>('changeCount') ?? 0;
  } catch (_) {
    return 0;
  }
}

/// True when the current pasteboard carries the community privacy markers
/// (org.nspasteboard.ConcealedType / TransientType / AutoGeneratedType) that
/// password managers use to opt out of clipboard history.
Future<bool> shouldBeIgnored() async {
  try {
    return await _ch.invokeMethod<bool>('shouldBeIgnored') ?? false;
  } catch (_) {
    return false;
  }
}

/// clearContents() — the post-secret-copy scrub.
Future<bool> clear() async {
  try {
    return await _ch.invokeMethod<bool>('clear') ?? false;
  } catch (_) {
    return false;
  }
}

/// Add the concealed/transient markers to whatever is on the pasteboard now.
Future<bool> markSensitive() async {
  try {
    return await _ch.invokeMethod<bool>('markSensitive') ?? false;
  } catch (_) {
    return false;
  }
}

/// Replace the pasteboard with [text] plus the concealed/transient markers, so
/// other history tools skip it.
Future<bool> writeSensitiveText(String text) async {
  try {
    return await _ch.invokeMethod<bool>('writeSensitiveText', {'text': text}) ??
        false;
  } catch (_) {
    return false;
  }
}

/// Replace the pasteboard with [text] plus whatever formatting flavors came
/// with it, rich types declared ahead of `.string` so apps that understand them
/// prefer them. [rtf] is raw RTF bytes; [html] is a bare fragment (the Swift
/// side adds the utf-8 charset marker).
Future<bool> writeRich(
  String text, {
  String? html,
  Uint8List? rtf,
  bool sensitive = false,
}) async {
  try {
    return await _ch.invokeMethod<bool>('writeRich', {
          'text': text,
          'html': ?html,
          'rtf': ?rtf,
          'sensitive': sensitive,
        }) ??
        false;
  } catch (_) {
    return false;
  }
}

/// File paths from a Finder ⌘C (public.file-url pasteboard items), or empty.
Future<List<String>> filePaths() async {
  try {
    final r = await _ch.invokeMethod<List<Object?>>('filePaths');
    return r?.whereType<String>().toList() ?? const [];
  } catch (_) {
    return const [];
  }
}

/// Raw image bytes (TIFF, macOS's native raster pasteboard format) for sources
/// that don't also provide a PNG representation. Null when there is none.
Future<Uint8List?> rawImage() async {
  try {
    return await _ch.invokeMethod<Uint8List>('rawImage');
  } catch (_) {
    return null;
  }
}

/// Put a real file on the pasteboard (as a file URL), so it pastes as a file
/// in Finder — the CF_HDROP analog. Marks it sensitive like the Windows path.
Future<bool> writeFile(String path) async {
  try {
    return await _ch.invokeMethod<bool>('writeFile', {'path': path}) ?? false;
  } catch (_) {
    return false;
  }
}
